apiVersion: v1
kind: PersistentVolume
metadata:
  name: artemis-dev-pv
spec:
  capacity:
    storage: 4Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs-csi-inmediate
  hostPath:
    path: /amq

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artemis-pvc
  namespace: artemis-dev
spec:
  storageClassName: nfs-csi-inmediate
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
