apiVersion: v1
kind: PersistentVolume
metadata:
  name: artemis-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  hostPath:
    path: /amq
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: artemis-pvc
  namespace: artemis-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi